### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/mesakit#11]
This error is not consistent, but sometimes country-borders.osm is not found when testing borders.

[12:12 PM] Zhou, Yinyin
| 69 | 33s | pool-2-thread-2 | Progress | Information | [Loading] ┗━━━━ Processed relations in 1 millisecond ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ |
| 70 | 33s | pool-2-thread-2 | SerialPbfReader | Information | ┗━━━━ Completed processing in 2 milliseconds ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ |
| 71 | 33s | pool-2-thread-2 | Country.1 | Warning | Unable to load borders from pbf file '/Users/yyzhou/.mesakit/1.3.1-SNAPSHOT/map/region/borders/0.9.1/country-borders.osm.pbf': Couldn't open file for |
| | | | | | reading: /Users/yyzhou/.mesakit/1.3.1-SNAPSHOT/map/region/borders/0.9.1/country-borders.osm.pbf: /Users/yyzhou/.mesakit/1.3.1-SNAPSHOT/map/region/bord |
| | | | | | ers/0.9.1/country-borders.osm.pbf (No such file or directory) |
| | | | | | Exception in thread "pool-2-thread-2"java.io.FileNotFoundException: /Users/yyzhou/.mesakit/1.3.1-SNAPSHOT/map/region/borders/0.9.1/country-borders.osm |
| | | | | | .pbf (No such file or directory) |
| | | | | | at java.io.FileInputStream.open0(FileInputStream.java:-2) |
| | | | | | at java.io.FileInputStream.open(FileInputStream.java:211) |
| | | | | | at java.io.FileInputStream.<init>(FileInputStream.java:153) |
| | | | | | at com.telenav.kivakit.filesystem.local.LocalFile.onOpenForReading(LocalFile.java:211) |
| | | | | | at com.telenav.kivakit.filesystem.File.onOpenForReading(File.java:618) |
| | | | | | at com.telenav.kivakit.kernel.interfaces.io.Readable.openForReading(Readable.java:85) |
| | | | | | at com.telenav.mesakit.map.data.formats.pbf.processing.readers.SerialPbfReader.onProcess(SerialPbfReader.java:59) |
| | | | | | at com.telenav.mesakit.map.data.formats.pbf.processing.PbfDataSource.process(PbfDataSource.java:123) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadBordersFromPbf(BorderCache.java:738) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadBorders(BorderCache.java:612) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadBorders(BorderCache.java:306) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadIdentities(BorderCache.java:336) |
| | | | | | at com.telenav.mesakit.map.region.RegionType.loadIdentities(RegionType.java:231) |
| | | | | | at com.telenav.mesakit.map.region.Region.lambda.bootstrap.1(Region.java:245) |
| | | | | | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) |
| | | | | | at java.util.concurrent.ThreadPoolExecutor.Worker.run(ThreadPoolExecutor.java:630) |
| | | | | | at java.lang.Thread.run(Thread.java:831) |
| | | | | | Exception in thread "Kiva-Console-Log"java.lang.IllegalStateException: Couldn't open file for reading: /Users/yyzhou/.mesakit/1.3.1-SNAPSHOT/map/regio |
| | | | | | n/borders/0.9.1/country-borders.osm.pbf: /Users/yyzhou/.mesakit/1.3.1-SNAPSHOT/map/region/borders/0.9.1/country-borders.osm.pbf (No such file or direc |
| | | | | | tory) |
| | | | | | Exception in thread "pool-2-thread-2"java.io.FileNotFoundException: /Users/yyzhou/.mesakit/1.3.1-SNAPSHOT/map/region/borders/0.9.1/country-borders.osm |
| | | | | | .pbf (No such file or directory) |
| | | | | | at java.io.FileInputStream.open0(FileInputStream.java:-2) |
| | | | | | at java.io.FileInputStream.open(FileInputStream.java:211) |
| | | | | | at java.io.FileInputStream.<init>(FileInputStream.java:153) |
| | | | | | at com.telenav.kivakit.filesystem.local.LocalFile.onOpenForReading(LocalFile.java:211) |
| | | | | | at com.telenav.kivakit.filesystem.File.onOpenForReading(File.java:618) |
| | | | | | at com.telenav.kivakit.kernel.interfaces.io.Readable.openForReading(Readable.java:85) |
| | | | | | at com.telenav.mesakit.map.data.formats.pbf.processing.readers.SerialPbfReader.onProcess(SerialPbfReader.java:59) |
| | | | | | at com.telenav.mesakit.map.data.formats.pbf.processing.PbfDataSource.process(PbfDataSource.java:123) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadBordersFromPbf(BorderCache.java:738) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadBorders(BorderCache.java:612) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadBorders(BorderCache.java:306) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadIdentities(BorderCache.java:336) |
| | | | | | at com.telenav.mesakit.map.region.RegionType.loadIdentities(RegionType.java:231) |
| | | | | | at com.telenav.mesakit.map.region.Region.lambda.bootstrap.1(Region.java:245) |
| | | | | | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) |
| | | | | | at java.util.concurrent.ThreadPoolExecutor.Worker.run(ThreadPoolExecutor.java:630) |
| | | | | | at java.lang.Thread.run(Thread.java:831) |
| | | | | | at com.telenav.kivakit.kernel.messaging.Message.throwAsIllegalStateException(Message.java:431) |
| | | | | | at com.telenav.kivakit.kernel.messaging.Transceiver.fatal(Transceiver.java:186) |
| | | | | | at com.telenav.kivakit.filesystem.local.LocalFile.onOpenForReading(LocalFile.java:215) |
| | | | | | at com.telenav.kivakit.filesystem.File.onOpenForReading(File.java:618) |
| | | | | | at com.telenav.kivakit.kernel.interfaces.io.Readable.openForReading(Readable.java:85) |
| | | | | | at com.telenav.mesakit.map.data.formats.pbf.processing.readers.SerialPbfReader.onProcess(SerialPbfReader.java:59) |
| | | | | | at com.telenav.mesakit.map.data.formats.pbf.processing.PbfDataSource.process(PbfDataSource.java:123) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadBordersFromPbf(BorderCache.java:738) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadBorders(BorderCache.java:612) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadBorders(BorderCache.java:306) |
| | | | | | at com.telenav.mesakit.map.region.border.cache.BorderCache.loadIdentities(BorderCache.java:336) |
| | | | | | at com.telenav.mesakit.map.region.RegionType.loadIdentities(RegionType.java:231) |
| | | | | | at com.telenav.mesakit.map.region.Region.lambda.bootstrap.1(Region.java:245) |
| | | | | | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) |
| | | | | | at java.util.concurrent.ThreadPoolExecutor.Worker.run(ThreadPoolExecutor.java:630) |
| | | | | | at java.lang.Thread.run(Thread.java:831) |
| 72 | 33s | pool-2-thread-2 | Country.1 | Problem | Unable to load country borders |
Exception in thread "pool-2-thread-5" java.lang.AssertionError: Couldn't download valid border data

**Comment by jonathanl-telenav** [comment]
This was due to a regression in Lazy in kivakit-kernel
